=== vknue/Mahjong/gameMoves.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT gameMoves (gameMove+)>
        <!ELEMENT gameMove (player, gameMoveType, tileName, time)>
        <!ELEMENT player (#PCDATA)>
        <!ELEMENT gameMoveType (#PCDATA)>
        <!ELEMENT tileName (#PCDATA)>
        <!ELEMENT time (#PCDATA)>

=== vknue/Mahjong/replayAdvisor.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE gameMoves SYSTEM "gameMoves.dtd">
<gameMoves>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou8</tileName>
        <time>1706102280160</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou2</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou5</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man5</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou6</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man7</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Nan</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou6</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Pin8</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou7</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou3</tileName>
        <time>1706102280161</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man3</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Ton</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou4</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man9</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Pin1</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Ton</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Chun</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man4</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Pin4</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Nan</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Hatsu</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Man5</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou1</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Sou8</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Pin2</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DRAW_FROM_TABLE</gameMoveType>
        <tileName>Pin3</tileName>
        <time>1706102280162</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Man9</tileName>
        <time>1706102374711</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Man9</tileName>
        <time>1706102384456</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Man3</tileName>
        <time>1706102385253</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Man3</tileName>
        <time>1706102387135</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Pin3</tileName>
        <time>1706102389270</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Pin3</tileName>
        <time>1706102399319</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Sou4</tileName>
        <time>1706102400478</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Sou4</tileName>
        <time>1706102403726</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Pin8</tileName>
        <time>1706102407767</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Pin8</tileName>
        <time>1706102412110</time>
    </gameMove>
    <gameMove>
        <player>SERVER</player>
        <gameMoveType>DISCARD</gameMoveType>
        <tileName>Sou6</tileName>
        <time>1706102412910</time>
    </gameMove>
    <gameMove>
        <player>CLIENT</player>
        <gameMoveType>PONG</gameMoveType>
        <tileName>Sou6</tileName>
        <time>1706102415304</time>
    </gameMove>
</gameMoves>
